/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as DashboardEventsIndexRouteImport } from './routes/_dashboard.events.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardEventsScheduleRouteImport } from './routes/_dashboard.events.schedule'
import { Route as DashboardEventsEventIdRouteImport } from './routes/_dashboard.events.$eventId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsIndexRoute = DashboardEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEventsScheduleRoute = DashboardEventsScheduleRouteImport.update({
  id: '/events/schedule',
  path: '/events/schedule',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsEventIdRoute = DashboardEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/events/$eventId': typeof DashboardEventsEventIdRoute
  '/events/schedule': typeof DashboardEventsScheduleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/events/': typeof DashboardEventsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof DashboardIndexRoute
  '/events/$eventId': typeof DashboardEventsEventIdRoute
  '/events/schedule': typeof DashboardEventsScheduleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/events': typeof DashboardEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/events/$eventId': typeof DashboardEventsEventIdRoute
  '/_dashboard/events/schedule': typeof DashboardEventsScheduleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_dashboard/events/': typeof DashboardEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/events/$eventId'
    | '/events/schedule'
    | '/api/auth/$'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/events/$eventId'
    | '/events/schedule'
    | '/api/auth/$'
    | '/events'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/'
    | '/_dashboard/events/$eventId'
    | '/_dashboard/events/schedule'
    | '/api/auth/$'
    | '/_dashboard/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/events/': {
      id: '/_dashboard/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof DashboardEventsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/events/schedule': {
      id: '/_dashboard/events/schedule'
      path: '/events/schedule'
      fullPath: '/events/schedule'
      preLoaderRoute: typeof DashboardEventsScheduleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/events/$eventId': {
      id: '/_dashboard/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof DashboardEventsEventIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEventsEventIdRoute: typeof DashboardEventsEventIdRoute
  DashboardEventsScheduleRoute: typeof DashboardEventsScheduleRoute
  DashboardEventsIndexRoute: typeof DashboardEventsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEventsEventIdRoute: DashboardEventsEventIdRoute,
  DashboardEventsScheduleRoute: DashboardEventsScheduleRoute,
  DashboardEventsIndexRoute: DashboardEventsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
