/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as ApiEventsIndexRouteImport } from './routes/api/events/index'
import { Route as ApiCustomersIndexRouteImport } from './routes/api/customers/index'
import { Route as DashboardPurchasesIndexRouteImport } from './routes/_dashboard.purchases.index'
import { Route as DashboardEventsIndexRouteImport } from './routes/_dashboard.events.index'
import { Route as ApiEventsEventIdRouteImport } from './routes/api/events/$eventId'
import { Route as ApiCustomersMeRouteImport } from './routes/api/customers/me'
import { Route as ApiCustomersLinkRouteImport } from './routes/api/customers/link'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardEventsScheduleRouteImport } from './routes/_dashboard.events.schedule'
import { Route as DashboardEventsEventIdRouteImport } from './routes/_dashboard.events.$eventId'
import { Route as ApiTicketsPurchaseIndexRouteImport } from './routes/api/tickets/purchase/index'
import { Route as ApiTicketsPurchaseReserveRouteImport } from './routes/api/tickets/purchase/reserve'
import { Route as ApiTicketsPurchaseConfirmRouteImport } from './routes/api/tickets/purchase/confirm'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiEventsIndexRoute = ApiEventsIndexRouteImport.update({
  id: '/api/events/',
  path: '/api/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomersIndexRoute = ApiCustomersIndexRouteImport.update({
  id: '/api/customers/',
  path: '/api/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPurchasesIndexRoute = DashboardPurchasesIndexRouteImport.update({
  id: '/purchases/',
  path: '/purchases/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsIndexRoute = DashboardEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiEventsEventIdRoute = ApiEventsEventIdRouteImport.update({
  id: '/api/events/$eventId',
  path: '/api/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomersMeRoute = ApiCustomersMeRouteImport.update({
  id: '/api/customers/me',
  path: '/api/customers/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomersLinkRoute = ApiCustomersLinkRouteImport.update({
  id: '/api/customers/link',
  path: '/api/customers/link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEventsScheduleRoute = DashboardEventsScheduleRouteImport.update({
  id: '/events/schedule',
  path: '/events/schedule',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsEventIdRoute = DashboardEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiTicketsPurchaseIndexRoute = ApiTicketsPurchaseIndexRouteImport.update({
  id: '/api/tickets/purchase/',
  path: '/api/tickets/purchase/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTicketsPurchaseReserveRoute =
  ApiTicketsPurchaseReserveRouteImport.update({
    id: '/api/tickets/purchase/reserve',
    path: '/api/tickets/purchase/reserve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTicketsPurchaseConfirmRoute =
  ApiTicketsPurchaseConfirmRouteImport.update({
    id: '/api/tickets/purchase/confirm',
    path: '/api/tickets/purchase/confirm',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/events/$eventId': typeof DashboardEventsEventIdRoute
  '/events/schedule': typeof DashboardEventsScheduleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/customers/link': typeof ApiCustomersLinkRoute
  '/api/customers/me': typeof ApiCustomersMeRoute
  '/api/events/$eventId': typeof ApiEventsEventIdRoute
  '/events/': typeof DashboardEventsIndexRoute
  '/purchases/': typeof DashboardPurchasesIndexRoute
  '/api/customers/': typeof ApiCustomersIndexRoute
  '/api/events/': typeof ApiEventsIndexRoute
  '/api/tickets/purchase/confirm': typeof ApiTicketsPurchaseConfirmRoute
  '/api/tickets/purchase/reserve': typeof ApiTicketsPurchaseReserveRoute
  '/api/tickets/purchase/': typeof ApiTicketsPurchaseIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof DashboardIndexRoute
  '/events/$eventId': typeof DashboardEventsEventIdRoute
  '/events/schedule': typeof DashboardEventsScheduleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/customers/link': typeof ApiCustomersLinkRoute
  '/api/customers/me': typeof ApiCustomersMeRoute
  '/api/events/$eventId': typeof ApiEventsEventIdRoute
  '/events': typeof DashboardEventsIndexRoute
  '/purchases': typeof DashboardPurchasesIndexRoute
  '/api/customers': typeof ApiCustomersIndexRoute
  '/api/events': typeof ApiEventsIndexRoute
  '/api/tickets/purchase/confirm': typeof ApiTicketsPurchaseConfirmRoute
  '/api/tickets/purchase/reserve': typeof ApiTicketsPurchaseReserveRoute
  '/api/tickets/purchase': typeof ApiTicketsPurchaseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/events/$eventId': typeof DashboardEventsEventIdRoute
  '/_dashboard/events/schedule': typeof DashboardEventsScheduleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/customers/link': typeof ApiCustomersLinkRoute
  '/api/customers/me': typeof ApiCustomersMeRoute
  '/api/events/$eventId': typeof ApiEventsEventIdRoute
  '/_dashboard/events/': typeof DashboardEventsIndexRoute
  '/_dashboard/purchases/': typeof DashboardPurchasesIndexRoute
  '/api/customers/': typeof ApiCustomersIndexRoute
  '/api/events/': typeof ApiEventsIndexRoute
  '/api/tickets/purchase/confirm': typeof ApiTicketsPurchaseConfirmRoute
  '/api/tickets/purchase/reserve': typeof ApiTicketsPurchaseReserveRoute
  '/api/tickets/purchase/': typeof ApiTicketsPurchaseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/events/$eventId'
    | '/events/schedule'
    | '/api/auth/$'
    | '/api/customers/link'
    | '/api/customers/me'
    | '/api/events/$eventId'
    | '/events/'
    | '/purchases/'
    | '/api/customers/'
    | '/api/events/'
    | '/api/tickets/purchase/confirm'
    | '/api/tickets/purchase/reserve'
    | '/api/tickets/purchase/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/events/$eventId'
    | '/events/schedule'
    | '/api/auth/$'
    | '/api/customers/link'
    | '/api/customers/me'
    | '/api/events/$eventId'
    | '/events'
    | '/purchases'
    | '/api/customers'
    | '/api/events'
    | '/api/tickets/purchase/confirm'
    | '/api/tickets/purchase/reserve'
    | '/api/tickets/purchase'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/'
    | '/_dashboard/events/$eventId'
    | '/_dashboard/events/schedule'
    | '/api/auth/$'
    | '/api/customers/link'
    | '/api/customers/me'
    | '/api/events/$eventId'
    | '/_dashboard/events/'
    | '/_dashboard/purchases/'
    | '/api/customers/'
    | '/api/events/'
    | '/api/tickets/purchase/confirm'
    | '/api/tickets/purchase/reserve'
    | '/api/tickets/purchase/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCustomersLinkRoute: typeof ApiCustomersLinkRoute
  ApiCustomersMeRoute: typeof ApiCustomersMeRoute
  ApiEventsEventIdRoute: typeof ApiEventsEventIdRoute
  ApiCustomersIndexRoute: typeof ApiCustomersIndexRoute
  ApiEventsIndexRoute: typeof ApiEventsIndexRoute
  ApiTicketsPurchaseConfirmRoute: typeof ApiTicketsPurchaseConfirmRoute
  ApiTicketsPurchaseReserveRoute: typeof ApiTicketsPurchaseReserveRoute
  ApiTicketsPurchaseIndexRoute: typeof ApiTicketsPurchaseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/events/': {
      id: '/api/events/'
      path: '/api/events'
      fullPath: '/api/events/'
      preLoaderRoute: typeof ApiEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customers/': {
      id: '/api/customers/'
      path: '/api/customers'
      fullPath: '/api/customers/'
      preLoaderRoute: typeof ApiCustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/purchases/': {
      id: '/_dashboard/purchases/'
      path: '/purchases'
      fullPath: '/purchases/'
      preLoaderRoute: typeof DashboardPurchasesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/events/': {
      id: '/_dashboard/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof DashboardEventsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/events/$eventId': {
      id: '/api/events/$eventId'
      path: '/api/events/$eventId'
      fullPath: '/api/events/$eventId'
      preLoaderRoute: typeof ApiEventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customers/me': {
      id: '/api/customers/me'
      path: '/api/customers/me'
      fullPath: '/api/customers/me'
      preLoaderRoute: typeof ApiCustomersMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customers/link': {
      id: '/api/customers/link'
      path: '/api/customers/link'
      fullPath: '/api/customers/link'
      preLoaderRoute: typeof ApiCustomersLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/events/schedule': {
      id: '/_dashboard/events/schedule'
      path: '/events/schedule'
      fullPath: '/events/schedule'
      preLoaderRoute: typeof DashboardEventsScheduleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/events/$eventId': {
      id: '/_dashboard/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof DashboardEventsEventIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/tickets/purchase/': {
      id: '/api/tickets/purchase/'
      path: '/api/tickets/purchase'
      fullPath: '/api/tickets/purchase/'
      preLoaderRoute: typeof ApiTicketsPurchaseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tickets/purchase/reserve': {
      id: '/api/tickets/purchase/reserve'
      path: '/api/tickets/purchase/reserve'
      fullPath: '/api/tickets/purchase/reserve'
      preLoaderRoute: typeof ApiTicketsPurchaseReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tickets/purchase/confirm': {
      id: '/api/tickets/purchase/confirm'
      path: '/api/tickets/purchase/confirm'
      fullPath: '/api/tickets/purchase/confirm'
      preLoaderRoute: typeof ApiTicketsPurchaseConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEventsEventIdRoute: typeof DashboardEventsEventIdRoute
  DashboardEventsScheduleRoute: typeof DashboardEventsScheduleRoute
  DashboardEventsIndexRoute: typeof DashboardEventsIndexRoute
  DashboardPurchasesIndexRoute: typeof DashboardPurchasesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEventsEventIdRoute: DashboardEventsEventIdRoute,
  DashboardEventsScheduleRoute: DashboardEventsScheduleRoute,
  DashboardEventsIndexRoute: DashboardEventsIndexRoute,
  DashboardPurchasesIndexRoute: DashboardPurchasesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCustomersLinkRoute: ApiCustomersLinkRoute,
  ApiCustomersMeRoute: ApiCustomersMeRoute,
  ApiEventsEventIdRoute: ApiEventsEventIdRoute,
  ApiCustomersIndexRoute: ApiCustomersIndexRoute,
  ApiEventsIndexRoute: ApiEventsIndexRoute,
  ApiTicketsPurchaseConfirmRoute: ApiTicketsPurchaseConfirmRoute,
  ApiTicketsPurchaseReserveRoute: ApiTicketsPurchaseReserveRoute,
  ApiTicketsPurchaseIndexRoute: ApiTicketsPurchaseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
